#!/usr/bin/env python3
"""Fix `title` on every case in data/cases/case_library.json.

The original title field was generated by naively truncating raw text
at a fixed character count, without being sentence- or boilerplate-aware.
That produced two kinds of bugs:

  1. Titles cut off mid-word/mid-sentence ("...A man in his forties with
     extremity and" instead of "...with extremity and groin lesions.")
  2. Titles bleeding into the actual case narrative (grabbing the title
     sentence AND the start of the next paragraph)

This script re-derives the title directly from each case's
case_text.txt: the line immediately after the "History of Present
Illness" heading is a boilerplate label (something like "IDSA 2001 Case
Summary:", "2014 May-June Featured Case:", etc.) followed by the actual
one-sentence case summary. We strip the label and take exactly the
first sentence — no more, no less.

A rare source-text quirk (3 cases) embeds a multi-sentence teaching
aside in parentheses *inside* the title sentence itself
(e.g. "A man with rapidly progressive (Tempo of onset ... virulence
factors.) arm pain and swelling.") — those asides are stripped out too.

A handful of cases (6, as of this writing) have no title/summary line
at all — the History of Present Illness section is empty and jumps
straight to the next section heading. For those, we fall back to the
first line of the `diagnosis` field, which in this corpus is
consistently a short label-style phrase (e.g. "Tularemia complicated by
brain abscesses").

Usage:
    python scripts/fix_case_titles.py            # writes case_library.json in place
    python scripts/fix_case_titles.py --dry-run   # prints a diff of changed titles only
"""

import argparse
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CASE_LIBRARY = REPO_ROOT / "data" / "cases" / "case_library.json"
ALL_CASES_DIR = REPO_ROOT / "data" / "cases" / "ID_Images" / "All_cases"

# Section headings that mean "there's no title/summary line here" if
# found immediately after "History of Present Illness".
SECTION_HEADINGS = {
    "past medical history", "physical examination", "studies",
    "diagnostic procedure(s) and result(s)", "treatment and followup",
    "discussion", "epidemiological history", "final diagnosis",
}

# Sentence boundary: a period/!/? followed by a space + capital letter,
# or by the end of the string.
SENT_END_RE = re.compile(r"^(.*?[.!?])(?:\s+[A-Z]|\s*$)", re.DOTALL)

# Multi-sentence parenthetical "teaching aside" — has its own internal
# sentence boundary, unlike a short clarifier like "(HIV)" or
# "(complicated by graft rejection)".
PAREN_ASIDE_RE = re.compile(r"\s*\([^()]*?[.!?]\s+[A-Z][^()]*?\)")


def strip_boilerplate_label(line: str) -> str:
    """Strip a leading 'label:' prefix, e.g. 'IDSA 2001 Case Summary:' or
    '2014 May-June Featured Case:'. The label is always short and always
    ends in a colon; the real sentence never starts with a colon this
    early, so stripping up to the first colon (if any, within a
    reasonable prefix length) is safe."""
    idx = line.find(":")
    if 0 <= idx <= 200:
        return line[idx + 1:].strip()
    return line.strip()


def strip_teaching_asides(text: str) -> str:
    return PAREN_ASIDE_RE.sub("", text)


def extract_title_from_line(line: str) -> str:
    stripped = strip_boilerplate_label(line)
    stripped = strip_teaching_asides(stripped)
    match = SENT_END_RE.match(stripped)
    return match.group(1).strip() if match else stripped.strip()


def fallback_title_from_diagnosis(diagnosis: str) -> str:
    first_line = (diagnosis or "").split("\n")[0].strip()
    if first_line and not first_line.endswith((".", "!", "?")):
        first_line += "."
    return first_line


def derive_title(case: dict) -> str:
    case_text_path = ALL_CASES_DIR / case["id"] / "case_text.txt"
    if not case_text_path.exists():
        return case["title"]  # nothing to re-derive from; leave as-is

    lines = case_text_path.read_text().split("\n")
    line2 = lines[1] if len(lines) > 1 else ""
    line2_stripped = line2.strip()

    looks_unusable = (
        not line2_stripped
        or line2_stripped.lower() in SECTION_HEADINGS
        or line2_stripped.lower().startswith("figure ")
    )
    if looks_unusable:
        return fallback_title_from_diagnosis(case.get("diagnosis", ""))

    title = extract_title_from_line(line2)
    # Guard against any other unforeseen garbage line (e.g. something
    # that slips past the checks above but still yields an unusably
    # short result) by falling back the same way.
    if len(title) < 10:
        return fallback_title_from_diagnosis(case.get("diagnosis", ""))
    return title


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                         help="Print changed titles without writing case_library.json")
    args = parser.parse_args()

    with open(CASE_LIBRARY) as f:
        cases = json.load(f)

    changed = 0
    for case in cases:
        new_title = derive_title(case)
        if new_title != case["title"]:
            changed += 1
            if args.dry_run and changed <= 40:
                print(f"{case['id']}:")
                print(f"  old: {case['title']!r}")
                print(f"  new: {new_title!r}")
        case["title"] = new_title

    print(f"\n{changed}/{len(cases)} titles changed")

    if args.dry_run:
        return

    with open(CASE_LIBRARY, "w") as f:
        json.dump(cases, f, indent=2)
    print(f"Wrote {CASE_LIBRARY}")


if __name__ == "__main__":
    main()
